# Generated by Django 2.1.5 on 2021-05-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(max_length=200, verbose_name='cliente')),
                ('comarca', models.CharField(max_length=200, verbose_name='comarca')),
                ('uf', models.CharField(max_length=200, verbose_name='uf')),
            ],
        ),
    ]
