# Generated by Django 2.0.5 on 2021-05-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='pasta',
            field=models.CharField(max_length=200, verbose_name='pasta'),
        ),
    ]
