# Generated by Django 2.1.5 on 2021-05-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('cliente', models.CharField(max_length=200, verbose_name='cliente')),
                ('arquivo', models.FileField(upload_to='planilhas/')),
            ],
        ),
    ]
