# Generated by Django 2.1.5 on 2021-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_processo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilha',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
