# Generated by Django 2.1.5 on 2021-05-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_processo', '0002_planilha_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilha',
            name='activated',
        ),
    ]
